import React, { useState, useRef, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import Header from "../../components/header/Header";
import "./Reports.css";

export default function Reports({ isDarkMode, toggleTheme, sidebarCollapsed }) {
  const navigate = useNavigate();
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("All");
  const [reportType, setReportType] = useState("");
  const [dateRange, setDateRange] = useState("");
  const [exportFormat, setExportFormat] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const [isExpanded, setIsExpanded] = useState(false);
  const [showMenu, setShowMenu] = useState(false);
  const [hoveredSegment, setHoveredSegment] = useState(null);
  const [hoveredBar, setHoveredBar] = useState(null);
  const [rowMenuOpen, setRowMenuOpen] = useState(null);
  const rowMenuRef = useRef(null);

  // Close row menu on outside click
  useEffect(() => {
    const handler = (e) => {
      if (rowMenuRef.current && !rowMenuRef.current.contains(e.target)) {
        setRowMenuOpen(null);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  const handleBarHover = (event, month, value) => {
    const x = parseFloat(event.target.getAttribute("x")) + parseFloat(event.target.getAttribute("width")) / 2;
    const y = parseFloat(event.target.getAttribute("y"));
    setHoveredBar({ month, value, x, y });
  };

  const handleBarLeave = () => setHoveredBar(null);

  const reportsData = [
    { id: 1, name: "Q3 Funding Summary",       type: "Funding Analytics",  generatedBy: "Admin User", date: "2025-09-15", format: "PDF"   },
    { id: 2, name: "Investor Activity Aug 2025",type: "Investor Activity",  generatedBy: "System",     date: "2025-09-30", format: "Excel" },
    { id: 3, name: "Zakat Compliance Report",   type: "Zakat Compliance",   generatedBy: "Admin User", date: "2025-10-15", format: "PDF"   },
  ];

  const filteredData = reportsData.filter(item => {
    const matchesSearch =
      item.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.type.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = statusFilter === "All" || item.format === statusFilter;
    return matchesSearch && matchesStatus;
  });

  const handleGenerate = async () => {
    if (!reportType || !dateRange || !exportFormat) {
      alert("Please fill in all fields to generate a report");
      return;
    }
    const button = document.querySelector(".em-reports-generate-btn");
    if (button) { button.classList.add("loading"); button.disabled = true; }
    try {
      await new Promise(resolve => setTimeout(resolve, 2000));
      alert(`Report generated successfully!`);
      setReportType(""); setDateRange(""); setExportFormat("");
    } catch (e) {
      alert("Error generating report. Please try again.");
    } finally {
      if (button) { button.classList.remove("loading"); button.disabled = false; }
    }
  };

  const handleDownload = (item) => {
    const mockContent = `Report: ${item.name}\nType: ${item.type}\nGenerated By: ${item.generatedBy}\nDate: ${item.date}\nFormat: ${item.format}`;
    const blob = new Blob([mockContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${item.name.replace(/\s+/g, "_")}.${item.format.toLowerCase()}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className={`em-reports-container${isDarkMode ? " dark" : ""}`} data-sidebar-collapsed={sidebarCollapsed}>
      <Header isDarkMode={isDarkMode} toggleTheme={toggleTheme} sidebarCollapsed={sidebarCollapsed} />

      <main className="em-reports-main">
        {/* Page Header */}
        <div className="em-reports-page-header">
          <div>
            <h1 className="em-reports-title">Reports & Analytics</h1>
            <p className="em-reports-subtitle">Generate and download comprehensive platform reports</p>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="em-reports-stats-row">
          {[
            { icon: "blue", label: "Total Reports",     value: "148", sub: "Generated this year",   trend: "+12%", trendColor: "#00B031", trendBg: "rgba(0,176,49,0.08)" },
            { icon: "green",  label: "Schedule Reports", value: "12",  sub: "Active automations",   trend: "+3",   trendColor: "#00B031", trendBg: "rgba(0,176,49,0.08)" },
            { icon: "purple", label: "Recent Downloads", value: "42",  sub: "Last 30 days",         trend: "+8",   trendColor: "#8200DB", trendBg: "rgba(130,0,219,0.08)" },
            { icon: "orange", label: "Export Formats",   value: "6",   sub: "PDF, Excel, CSV, JSON",trend: "+8",   trendColor: "#FF6900", trendBg: "rgba(255,105,0,0.08)" },
          ].map((card, i) => (
            <div className="em-reports-stat-card" key={i}>
              <div className="em-reports-stat-header">
                <div className={`em-reports-icon-wrapper ${card.icon}-icon`}>
                  {i === 0 && <svg width="24" height="24" viewBox="0 0 24 24" fill="none"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8L14 2z" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><path d="M14 2v6h6M16 13H8M16 17H8M10 9H8" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>}
                  {i === 1 && <svg width="24" height="24" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="10" stroke="white" strokeWidth="2"/><path d="M12 6v6l3 3" stroke="white" strokeWidth="2" strokeLinecap="round"/></svg>}
                  {i === 2 && <svg width="24" height="24" viewBox="0 0 24 24" fill="none"><path d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>}
                  {i === 3 && <svg width="24" height="24" viewBox="0 0 24 24" fill="none"><path d="M15 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V7L15 2z" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><path d="M14 2v4a2 2 0 002 2h4M8 13h2M14 13h2M8 17h2M14 17h2" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>}
                </div>
                <div className="em-reports-trend-pill" style={{ color: card.trendColor, background: card.trendBg }}>
                  <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M1 9L4.5 5.5L6.5 7.5L11 3" stroke={card.trendColor} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/><path d="M7 3H11V7" stroke={card.trendColor} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>
                  <span>{card.trend}</span>
                </div>
              </div>
              <div className="em-reports-stat-body">
                <h3 className="em-reports-card-title">{card.label}</h3>
                <div className="em-reports-card-value">{card.value}</div>
                <div className="em-reports-card-divider" />
                <p className="em-reports-card-subtext">{card.sub}</p>
              </div>
            </div>
          ))}
        </div>

        {/* Charts Row */}
        <div className="em-reports-charts">
          {/* Donut Chart */}
          <div className="em-reports-chart-card">
            <div className="em-reports-chart-header">
              <div className="em-reports-title-section">
                <div className="em-reports-title-with-info">
                  <h3 className="em-reports-chart-title">Report Type Distribution</h3>
                  <button className="info-btn" title="Information"><svg width="16" height="16" viewBox="0 0 16 16" fill="none"><circle cx="8" cy="8" r="8" fill="#AFAFAF"/><path fillRule="evenodd" clipRule="evenodd" d="M9.30469 5.24219C9.42969 5.02344 9.5 4.76953 9.5 4.5C9.5 3.67188 8.82812 3 8 3C7.17188 3 6.5 3.67188 6.5 4.5C6.5 5.32812 7.17188 6 8 6C8.55859 6 9.04688 5.69531 9.30469 5.24219ZM7 7H7.5H8.5C9.05273 7 9.5 7.44727 9.5 8V9V13C9.5 13.5527 9.05273 14 8.5 14C7.94727 14 7.5 13.5527 7.5 13V9.75C7.5 9.33594 7.16406 9 6.75 9C6.33594 9 6 8.66406 6 8.25V8C6 7.64844 6.18164 7.33789 6.45508 7.16016C6.61133 7.05859 6.79883 7 7 7Z" fill="white"/></svg></button>
                </div>
                <p className="em-reports-chart-subtitle">Breakdown by report category</p>
              </div>
              <div className="header-actions">
                <button className={`expand-btn${isExpanded ? " expanded" : ""}`} onClick={() => setIsExpanded(!isExpanded)}><svg width="21" height="21" viewBox="0 0 21 21" fill="none"><path d="M8.59019 16.3212H4.29507V12.026M12.0263 4.29483H16.3214V8.58994" stroke="#888888" strokeWidth="1.28853" strokeLinecap="round" strokeLinejoin="round"/></svg></button>
                <button className="edit-btn"><svg width="21" height="21" viewBox="0 0 21 21" fill="none"><path d="M12.6866 4.44129C13.2312 3.89915 14.112 3.90017 14.6554 4.44358L16.1735 5.96172C16.7169 6.50505 16.718 7.38562 16.176 7.93033L7.44958 16.7014L3.91558 16.7013L3.91558 13.1716L12.6866 4.44129Z" stroke="#888888" strokeWidth="1.28853" strokeLinecap="round" strokeLinejoin="round"/><path d="M11.5802 5.55095L15.0647 9.03543" stroke="#888888" strokeWidth="1.28853" strokeLinecap="round"/></svg></button>
                <button className={`more-options${showMenu ? " active" : ""}`} onClick={() => setShowMenu(!showMenu)}><svg width="21" height="21" viewBox="0 0 21 21" fill="none"><circle cx="5.155" cy="10.308" r="1.59" fill="#888888"/><circle cx="10.31" cy="10.308" r="1.59" fill="#888888"/><circle cx="15.464" cy="10.308" r="1.59" fill="#888888"/></svg></button>
              </div>
            </div>
            <div className="em-reports-chart-content-vertical">
              <div className="em-reports-donut-section">
                <svg viewBox="0 0 241 241" className="em-reports-donut-chart" fill="none">
                  {[ 
                    { seg: "funding",       d: "M234.737 120.671C234.737 93.3941 225.019 67.0091 207.326 46.2485C189.633 25.4879 165.122 11.7099 138.19 7.38565L131.575 48.5804C148.714 51.3323 164.312 60.1001 175.571 73.3113C186.83 86.5226 193.015 103.313 193.015 120.671H234.737Z", fill: "#3B82F6" },
                    { seg: "investor",      d: "M132.236 6.58819C110.62 4.26991 88.7909 8.14024 69.2899 17.7485C49.789 27.3567 33.419 42.3074 22.0864 60.8593L57.6914 82.6089C64.9031 70.8031 75.3204 61.289 87.73 55.1747C100.14 49.0604 114.031 46.5974 127.786 48.0727L132.236 6.58819Z", fill: "#10B981" },
                    { seg: "startup",       d: "M19.0913 66.0683C10.983 81.0525 6.31344 97.6544 5.42178 114.668C4.53012 131.682 7.43869 148.681 13.9363 164.431L52.5054 148.519C48.3705 138.497 46.5196 127.679 47.087 116.852C47.6544 106.025 50.6259 95.46 55.7858 85.9246L19.0913 66.0683Z", fill: "#8B5CF6" },
                    { seg: "tokenization", d: "M16.3713 169.923C28.4215 195.279 49.3499 215.337 75.1945 226.301L91.4877 187.891C75.0411 180.914 61.7231 168.15 54.0548 152.014L16.3713 169.923Z", fill: "#F59E0B" },
                    { seg: "zakat",         d: "M80.7843 228.499C102.696 236.468 126.515 237.572 149.069 231.666L138.499 191.304C124.146 195.063 108.988 194.36 95.045 189.289L80.7843 228.499Z", fill: "#EC4899" },
                    { seg: "platform",      d: "M154.838 229.992C177.053 222.912 196.584 209.233 210.829 190.776C225.075 172.319 233.36 149.96 234.58 126.676L192.915 124.493C192.138 139.31 186.866 153.538 177.801 165.284C168.735 177.029 156.307 185.734 142.17 190.239L154.838 229.992Z", fill: "#06B6D4" },
                  ].map(({ seg, d, fill }) => (
                    <path key={seg} d={d} fill={fill} stroke="white" strokeWidth="1.04306"
                      className="donut-segment"
                      onMouseEnter={() => setHoveredSegment(seg)}
                      onMouseLeave={() => setHoveredSegment(null)}
                      style={{ cursor: "pointer", opacity: hoveredSegment && hoveredSegment !== seg ? 0.5 : 1, transition: "opacity 0.2s, transform 0.2s", transformOrigin: "120px 120px", transform: hoveredSegment === seg ? "scale(1.04)" : "scale(1)" }}
                    />
                  ))}
                  <circle cx="120.183" cy="120" r="119.519" stroke="#DFDFF2" strokeWidth="0.962003" fill="none"/>
                  {/* Inner circle for donut hole, color changes with dark mode */}
                  <circle cx="120.183" cy="120" r="65" fill={isDarkMode ? '#23232A' : 'white'} />
                </svg>
              </div>
              <div className="em-reports-chart-legend-figma" style={{ display: 'flex', gap: '276px', justifyContent: 'center' }}>
                {[
                  [{ seg: "funding", color: "#3B82F6", label: "Funding", value: 35 }, { seg: "startup", color: "#8B5CF6", label: "Startup", value: 22 }, { seg: "zakat", color: "#EC4899", label: "Zakat", value: 15 }],
                  [{ seg: "investor", color: "#10B981", label: "Investor", value: 28 }, { seg: "tokenization", color: "#F59E0B", label: "Tokenization", value: 18 }, { seg: "platform", color: "#06B6D4", label: "Platform", value: 30 }],
                ].map((col, ci) => (
                  <div className="em-reports-legend-column" key={ci}>
                    {col.map(({ seg, color, label, value }) => (
                      <div key={seg} className={`em-reports-legend-item-figma${hoveredSegment === seg ? " highlighted" : ""}`}
                        onMouseEnter={() => setHoveredSegment(seg)}
                        onMouseLeave={() => setHoveredSegment(null)}
                        style={{ cursor: "pointer" }}
                      >
                        <div className="em-reports-legend-indicator" style={{ background: color }} />
                        <span className="em-reports-legend-label-figma">{label}</span>
                        <span className="em-reports-legend-value-figma">{value}</span>
                      </div>
                    ))}
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Bar Chart */}
          <div className="em-reports-chart-card">
            <div className="em-reports-chart-header">
              <div className="em-reports-title-section">
                <div className="em-reports-title-with-info">
                  <h3 className="em-reports-chart-title">Reports Generated</h3>
                  <button className="info-btn"><svg width="16" height="16" viewBox="0 0 16 16" fill="none"><circle cx="8" cy="8" r="8" fill="#AFAFAF"/><path fillRule="evenodd" clipRule="evenodd" d="M9.30469 5.24219C9.42969 5.02344 9.5 4.76953 9.5 4.5C9.5 3.67188 8.82812 3 8 3C7.17188 3 6.5 3.67188 6.5 4.5C6.5 5.32812 7.17188 6 8 6C8.55859 6 9.04688 5.69531 9.30469 5.24219ZM7 7H7.5H8.5C9.05273 7 9.5 7.44727 9.5 8V9V13C9.5 13.5527 9.05273 14 8.5 14C7.94727 14 7.5 13.5527 7.5 13V9.75C7.5 9.33594 7.16406 9 6.75 9C6.33594 9 6 8.66406 6 8.25V8C6 7.64844 6.18164 7.33789 6.45508 7.16016C6.61133 7.05859 6.79883 7 7 7Z" fill="white"/></svg></button>
                </div>
                <p className="em-reports-chart-subtitle">Last 6 months trend</p>
              </div>
              <div className="header-actions">
                <button className={`expand-btn${isExpanded ? " expanded" : ""}`} onClick={() => setIsExpanded(!isExpanded)}><svg width="21" height="21" viewBox="0 0 21 21" fill="none"><path d="M8.59019 16.3212H4.29507V12.026M12.0263 4.29483H16.3214V8.58994" stroke="#888888" strokeWidth="1.28853" strokeLinecap="round" strokeLinejoin="round"/></svg></button>
                <button className="edit-btn"><svg width="21" height="21" viewBox="0 0 21 21" fill="none"><path d="M12.6866 4.44129C13.2312 3.89915 14.112 3.90017 14.6554 4.44358L16.1735 5.96172C16.7169 6.50505 16.718 7.38562 16.176 7.93033L7.44958 16.7014L3.91558 16.7013L3.91558 13.1716L12.6866 4.44129Z" stroke="#888888" strokeWidth="1.28853" strokeLinecap="round" strokeLinejoin="round"/><path d="M11.5802 5.55095L15.0647 9.03543" stroke="#888888" strokeWidth="1.28853" strokeLinecap="round"/></svg></button>
                <button className={`more-options${showMenu ? " active" : ""}`} onClick={() => setShowMenu(!showMenu)}><svg width="21" height="21" viewBox="0 0 21 21" fill="none"><circle cx="5.155" cy="10.308" r="1.59" fill="#888888"/><circle cx="10.31" cy="10.308" r="1.59" fill="#888888"/><circle cx="15.464" cy="10.308" r="1.59" fill="#888888"/></svg></button>
              </div>
            </div>
            <div className="em-reports-bar-chart-container">
              <svg viewBox="0 0 517 305" className="em-reports-bar-chart-figma">
                <defs>
                  <linearGradient id="barGradientHighlight" x1="0%" y1="0%" x2="0%" y2="100%">
                    <stop offset="0%" stopColor="#83A9FE"/>
                    <stop offset="100%" stopColor="#155DFC"/>
                  </linearGradient>
                </defs>
                {[258.721, 209.302, 158.915, 108.527, 58.1395, 7.75192].map((y, i) => (
                  <line key={i} x1="49.42" y1={y} x2="499.85" y2={y} stroke="#C1C1C1" strokeWidth="1.163" strokeLinecap="round" strokeDasharray={y === 258.721 ? "0" : "3.88 3.88"} strokeOpacity={y === 258.721 ? 0.5 : 1}/>
                ))}
                {["50","40","30","20","10","0"].map((v, i) => (
                  <text key={v} x={i === 3 ? "14.9" : i === 5 ? "28.2" : "18.5"} y={[13.2, 63.9, 115, 165.7, 216.5, 267.6][i]} fontSize="11" fill="#8D8D99" fontFamily="system-ui, sans-serif">{v}</text>
                ))}
                {["Jan","Feb","Mar","Apr","May","Jun","Jul"].map((m, i) => (
                  <text key={m} x={[69.3,131.5,196.4,261.7,325.5,395.4,463.3][i]} y="294.2" fontSize="11" fill="#8D8D99" fontFamily="system-ui, sans-serif">{m}</text>
                ))}
                {[
                  { x: 60.1,  y: 234.5, w: 55.1, h: 21.3,  rx: 10.6,  month: "Jan", value: 5,  highlight: false },
                  { x: 123.3, y: 131.8, w: 55.1, h: 124.0, rx: 12.2,  month: "Feb", value: 25, highlight: false },
                  { x: 186.4, y: 185.1, w: 55.1, h: 70.7,  rx: 12.2,  month: "Mar", value: 15, highlight: false },
                  { x: 249.6, y: 139.5, w: 55.1, h: 116.3, rx: 12.2,  month: "Apr", value: 23, highlight: false },
                  { x: 312.8, y: 85.3,  w: 55.1, h: 170.5, rx: 12.2,  month: "May", value: 35, highlight: false },
                  { x: 375.9, y: 131.8, w: 55.1, h: 124.0, rx: 12.2,  month: "Jun", value: 25, highlight: false },
                  { x: 439.1, y: 72.7,  w: 55.1, h: 172.1, rx: 12.2,  month: "Jul", value: 37, highlight: true  },
                ].map((bar) => (
                  <rect key={bar.month} x={bar.x} y={bar.y} width={bar.w} height={bar.h} rx={bar.rx}
                    fill={bar.highlight ? "url(#barGradientHighlight)" : hoveredBar?.month === bar.month ? "#6B8EE8" : "#83A9FE"}
                    className="chart-bar"
                    onMouseEnter={(e) => handleBarHover(e, bar.month, bar.value)}
                    onMouseLeave={handleBarLeave}
                    style={{ cursor: "pointer", transition: "fill 0.15s" }}
                  />
                ))}
                {hoveredBar && (
                  <g>
                    <rect x={hoveredBar.x - 42} y={hoveredBar.y - 58} width="84" height="47" rx="8" fill="#121212" opacity="0.95"/>
                    <text x={hoveredBar.x} y={hoveredBar.y - 38} fontSize="12" fill="white" textAnchor="middle" fontFamily="system-ui, sans-serif" fontWeight="600">{hoveredBar.month}</text>
                    <text x={hoveredBar.x} y={hoveredBar.y - 22} fontSize="11" fill="#BFDBFE" textAnchor="middle" fontFamily="system-ui, sans-serif">Reports: {hoveredBar.value}</text>
                  </g>
                )}
                // ...existing code...
              </svg>
            </div>
          </div>
        </div>

        {/* Generate New Report */}
        <div className="em-reports-generate-section">
          <div className="em-reports-generate-header">
            <div className="em-reports-generate-icon">
              <svg width="20" height="20" viewBox="0 0 20 20" fill="none"><path d="M13.7 17.4V10.67c0-.25.21-.46.47-.46.26 0 .46.2.46.46V17.4h.93c1.01 0 1.84-.83 1.84-1.84V4.44c0-1.01-.83-1.85-1.84-1.85H4.44c-1.01 0-1.85.83-1.85 1.85v11.12c0 1.01.83 1.84 1.85 1.84h.93v-4.42c0-.26.21-.47.46-.47.26 0 .46.21.46.47v4.42H8.15V8.36c0-.25.21-.46.46-.46.27 0 .47.2.47.46v9.04h1.85V4.9c0-.25.21-.46.46-.46.26 0 .46.21.46.46v12.5h1.85zM1.67 4.44c0-1.53 1.25-2.77 2.77-2.77h11.12c1.53 0 2.77 1.25 2.77 2.77v11.12c0 1.52-1.25 2.77-2.77 2.77H4.44c-1.52 0-2.77-1.25-2.77-2.77V4.44z" fill="white"/></svg>
            </div>
            <div>
              <h3 className="em-reports-generate-title">Generate New Report</h3>
              <p className="em-reports-generate-subtitle">Create custom reports with flexible parameters</p>
            </div>
          </div>
          <div className="em-reports-generate-controls">
            <div className="em-reports-generate-inputs">
              {[
                { label: "Report Type", value: reportType, setter: setReportType, placeholder: "Select report type", opts: [["funding","Funding Analytics"],["investor","Investor Activity"],["startup","Startup Performance"],["compliance","Compliance Report"]] },
                { label: "Date Range", value: dateRange, setter: setDateRange, placeholder: "Select date range", opts: [["7days","Last 7 days"],["30days","Last 30 days"],["quarter","This Quarter"],["year","This Year"]] },
                { label: "Export Format", value: exportFormat, setter: setExportFormat, placeholder: "Select format", opts: [["pdf","PDF"],["excel","Excel"],["csv","CSV"],["json","JSON"]] },
              ].map(({ label, value, setter, placeholder, opts }) => (
                <div className="em-reports-generate-field" key={label}>
                  <label className="em-reports-generate-label">{label}</label>
                  <select value={value} onChange={e => setter(e.target.value)} className="em-reports-generate-select">
                    <option value="">{placeholder}</option>
                    {opts.map(([v, l]) => <option key={v} value={v}>{l}</option>)}
                  </select>
                </div>
              ))}
            </div>
            <button className="em-reports-generate-btn" onClick={handleGenerate} disabled={!reportType || !dateRange || !exportFormat}>
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M8 10V2M14 10v2.667A1.333 1.333 0 0112.667 14H3.333A1.333 1.333 0 012 12.667V10" stroke="white" strokeWidth="1.333" strokeLinecap="round" strokeLinejoin="round"/><path d="M4.667 6.667L8 10l3.333-3.333" stroke="white" strokeWidth="1.333" strokeLinecap="round" strokeLinejoin="round"/></svg>
              Generate Report
            </button>
          </div>
        </div>

        {/* ──────────────────────────────────────────
            RECENT REPORTS TABLE — Figma Match
        ────────────────────────────────────────── */}
        <div className="rr-section">

          {/* Section header */}
          <div className="rr-header">
            <div className="rr-title-row">
              <h3 className="rr-title">Recent Reports</h3>
              <div className="rr-info-wrap">
                 <button className="info-btn" title="Information"><svg width="16" height="16" viewBox="0 0 16 16" fill="none"><circle cx="8" cy="8" r="8" fill="#AFAFAF"/><path fillRule="evenodd" clipRule="evenodd" d="M9.30469 5.24219C9.42969 5.02344 9.5 4.76953 9.5 4.5C9.5 3.67188 8.82812 3 8 3C7.17188 3 6.5 3.67188 6.5 4.5C6.5 5.32812 7.17188 6 8 6C8.55859 6 9.04688 5.69531 9.30469 5.24219ZM7 7H7.5H8.5C9.05273 7 9.5 7.44727 9.5 8V9V13C9.5 13.5527 9.05273 14 8.5 14C7.94727 14 7.5 13.5527 7.5 13V9.75C7.5 9.33594 7.16406 9 6.75 9C6.33594 9 6 8.66406 6 8.25V8C6 7.64844 6.18164 7.33789 6.45508 7.16016C6.61133 7.05859 6.79883 7 7 7Z" fill="white"/></svg></button>
                <div className="rr-info-tooltip">Reports remain available for 30 days after generation.</div>
              </div>
            </div>
            <p className="rr-subtitle">Previously generated reports available for download</p>
          </div>

          {/* Controls row */}
          <div className="rr-controls">
            {/* Status dropdown */}
            <div className="rr-status-wrap">
              <select
                value={statusFilter}
                onChange={e => { setStatusFilter(e.target.value); setCurrentPage(1); }}
                className="rr-status-select"
              >
                <option value="All">Status</option>
                <option value="PDF">PDF</option>
                <option value="Excel">Excel</option>
                <option value="CSV">CSV</option>
              </select>
              <span className="rr-status-arrow">
                <svg width="14" height="14" viewBox="0 0 16 16" fill="none">
                  <path d="M7.5 5.5L10.5 2.5L13.5 5.5" stroke="#121212" strokeWidth="1.13" strokeLinecap="round" strokeLinejoin="round"/>
                  <path d="M13.5 10.5L10.5 13.5L7.5 10.5" stroke="#121212" strokeWidth="1.13" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
              </span>
            </div>

            {/* Search box */}
            <div className="rr-search-wrap">
              <span className="rr-search-icon">
                <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                  <circle cx="6.6" cy="6.6" r="5.35" stroke="currentColor" strokeWidth="1.13"/>
                  <path d="M13.88 13.55L10.71 10.39" stroke="currentColor" strokeWidth="1.13" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
              </span>
              <input
                type="text"
                placeholder="Search"
                value={searchTerm}
                onChange={e => { setSearchTerm(e.target.value); setCurrentPage(1); }}
                className="rr-search-input"
              />
            </div>
          </div>

          {/* Table */}
          <div className="rr-table-wrap">
            <table className="rr-table">
              <thead>
                <tr className="rr-thead-row">
                  <th className="rr-th rr-th-name">REPORT NAME</th>
                  <th className="rr-th">TYPE</th>
                  <th className="rr-th">GENERATED BY</th>
                  <th className="rr-th">DATE</th>
                  <th className="rr-th">FORMAT</th>
                  <th className="rr-th rr-th-actions">ACTIONS</th>
                </tr>
              </thead>
              <tbody>
                {filteredData.length === 0 ? (
                  <tr>
                    <td colSpan={6} className="rr-empty">
                      <div className="rr-empty-inner">
                        <span>🔍</span>
                        <p>No reports match your search</p>
                        <button onClick={() => { setSearchTerm(""); setStatusFilter("All"); }}>Reset</button>
                      </div>
                    </td>
                  </tr>
                ) : filteredData.map(item => (
                  <tr key={item.id} className="rr-tr">
                    {/* Report name cell */}
                    <td className="rr-td rr-td-name">
                      <div className="rr-name-cell">
                        <div className="rr-doc-icon">
                          <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect width="24" height="24" rx="5" fill="#1C1C1F"/>
                            <path d="M13.33 5.33H8a1.33 1.33 0 00-1.33 1.33v10.67A1.33 1.33 0 008 18.67h8a1.33 1.33 0 001.33-1.33V9.33L13.33 5.33z" stroke="white" strokeLinecap="round" strokeLinejoin="round"/>
                            <path d="M13.33 5.33V9.33H17.33M14.67 12.67H9.33M14.67 15.33H9.33M10.67 10H10H9.33" stroke="white" strokeLinecap="round" strokeLinejoin="round"/>
                          </svg>
                        </div>
                        <span className="rr-name-text">{item.name}</span>
                      </div>
                    </td>
                    <td className="rr-td rr-td-muted">{item.type}</td>
                    <td className="rr-td rr-td-muted">{item.generatedBy}</td>
                    <td className="rr-td rr-td-muted">{item.date}</td>
                    <td className="rr-td">
                      <span className="rr-format-badge">{item.format}</span>
                    </td>
                    <td className="rr-td rr-td-actions">
                      {/* Download button */}
                      <button
                        className="rr-action-btn rr-download-btn"
                        title="Download"
                        onClick={() => handleDownload(item)}
                      >
                        <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                          <path d="M14 10v2.667A1.333 1.333 0 0112.667 14H3.333A1.333 1.333 0 012 12.667V10" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                          <path d="M4.667 6.667L8 10l3.333-3.333M8 10V2" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                        </svg>
                      </button>

                      {/* Three-dot menu */}
                      <div className="rr-menu-wrap" ref={rowMenuOpen === item.id ? rowMenuRef : null}>
                        <button
                          className="rr-action-btn rr-menu-btn"
                          title="More actions"
                          onClick={() => setRowMenuOpen(rowMenuOpen === item.id ? null : item.id)}
                        >
                          <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                            <circle cx="8" cy="3" r="1.5" fill="currentColor"/>
                            <circle cx="8" cy="8" r="1.5" fill="currentColor"/>
                            <circle cx="8" cy="13" r="1.5" fill="currentColor"/>
                          </svg>
                        </button>
                        {rowMenuOpen === item.id && (
                          <div className="rr-row-dropdown">
                            <button onClick={() => { handleDownload(item); setRowMenuOpen(null); }}>Download</button>
                            <button onClick={() => setRowMenuOpen(null)}>Share</button>
                            <button onClick={() => setRowMenuOpen(null)} className="rr-row-dropdown-danger">Delete</button>
                          </div>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Footer */}
          <div className="rr-footer">
            <div className="rr-showing">
              Showing{" "}
              <span className="rr-showing-badge">{String(filteredData.length).padStart(2, "0")}</span>
              {" "}/ 15 Results
            </div>
            <div className="rr-pagination">
              <button className="rr-page-btn rr-arrow" onClick={() => setCurrentPage(p => Math.max(1, p - 1))} disabled={currentPage === 1}>
                <svg width="18" height="18" viewBox="0 0 18 18" fill="none"><path d="M11 13L7 9L11 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>
              </button>
              {[1, 2, 3].map(n => (
                <button key={n} className={`rr-page-btn rr-page-num${currentPage === n ? " rr-page-active" : ""}`} onClick={() => setCurrentPage(n)}>{n}</button>
              ))}
              <span className="rr-page-dots">
                <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                  <circle cx="3" cy="8" r="1.2" fill="#717182"/><circle cx="8" cy="8" r="1.2" fill="#717182"/><circle cx="13" cy="8" r="1.2" fill="#717182"/>
                </svg>
              </span>
              <button className={`rr-page-btn rr-page-num${currentPage === 10 ? " rr-page-active" : ""}`} onClick={() => setCurrentPage(10)}>10</button>
              <button className="rr-page-btn rr-arrow" onClick={() => setCurrentPage(p => Math.min(10, p + 1))} disabled={currentPage === 10}>
                <svg width="18" height="18" viewBox="0 0 18 18" fill="none"><path d="M7 5L11 9L7 13" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>
              </button>
            </div>
          </div>

          {/* Disclaimer */}
          <div className="rr-disclaimer">
            Market data is updated in real-time. Prices are for reference only and may vary across exchanges.
          </div>
        </div>
        {/* end .rr-section */}

      </main>
    </div>
  );
}